# Generated by Django 6.0.5 on 2026-05-12 08:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('category', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PixelPilot', max_length=100)),
                ('tagline', models.CharField(default='Navigating Your Brand to Digital Success', max_length=300)),
                ('about_story', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(default='hello@pixelpilot.in', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('whatsapp', models.CharField(default='+919876543210', max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(default='month', max_length=20)),
                ('features', models.JSONField(default=list)),
                ('recommended', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_desc', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(default='fas fa-bullhorn', max_length=100)),
                ('highlighted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(blank=True, max_length=150)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before/')),
                ('after_image', models.ImageField(upload_to='portfolio/after/')),
                ('result', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('featured', models.BooleanField(default=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
        ),
    ]
